# Generated by Django 4.2.7 on 2024-02-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_pricetable_options_alter_pricetable_pt_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecard',
            options={'verbose_name': 'набор', 'verbose_name_plural': 'Наборы'},
        ),
        migrations.AlterField(
            model_name='pricecard',
            name='pc_value',
            field=models.CharField(max_length=30, verbose_name='Набор'),
        ),
    ]
